# Generated by Django 6.0.4 on 2026-04-09 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp'])]),
        ),
        migrations.AlterUniqueTogether(
            name='userconfirmation',
            unique_together={('user', 'code', 'is_confirmed')},
        ),
    ]
